---
- name: Add desktop repos
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [aur-{{ item.name }}]
      SigLevel = Optional TrustAll
      Server = https://github.com/evrardjp/aurci/releases/download/{{ item.name }}
  loop:
    - name: desktop
      when:
        - "'laptop' in group_names"
    - name: samus
      when:
        -  "ansible_hostname == 'laptop-chromebook'"
    - name: k8s
      when:
        -  "'master' in group_names or 'worker' in group_names"
