---
- name: Add repos
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [{{ repodetails[item]['reponame'] }}]
      SigLevel = Optional TrustAll
      Server = {{ repodetails[item]['repolocation'] }}
  loop: "{{ repos | default([]) }}"
