---
- name: Add desktop repos
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [aurci_{{ item.name }}]
      SigLevel = Optional TrustAll
      Server = https://github.com/evrardjp/aurci/releases/download/{{ item.name }}
  when: "item.when | bool"
  loop:
    - name: desktop
      when: "'laptop' in group_names"
    - name: samus
      when: "ansible_hostname == 'laptop-pixel'"
    - name: k8s
      when: "'k8s' in group_names"
