---
- import_playbook: enroll.yml
- import_playbook: in-memory-inventory.yml

- name: Run common configuration tasks
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - repos          # Install personal AUR repos
    - system-upgrade # Install personal AUR repos
    - base-software  # Install minimum software/clients to get things done

- name: Run roles based on group appartenance
  hosts: k8s:worker:master:server
  connection: local
  gather_facts: no
  roles:
    - poweroff-schedule # Ensures servers are stopped at the end of day.

- name: Configure users
  hosts: laptop
  connection: local
  gather_facts: no
  roles:
    - users # Ensures the local users are defined

- name: Configure dotfiles for user jean-philippe
  hosts: laptop
  gather_facts: yes
  become: true
  become_method: su
  become_user: jean-philippe
  roles:
    - dotfiles
