---
- name: Prepare groups
  hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Prepare the future groups based on hostname (remove domain and numbers)
      set_fact:
        cleanhostname: "{{ ansible_hostname.split('.')[0] | regex_replace('[0-9]*$','') }}"
    - name: Add groups based on hostname parts
      group_by:
        key: "{{ item }}"
      loop: "{{ cleanhostname.split('-') }}"
    - name: Show current groups
      debug:
        msg: "{{ groups }}"

- name: Run common configuration tasks
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - ansible-pull   # Ensures this will run on a regular basis
    - sshd           # Installs and configures SSHd
    - repos          # Install personal AUR repos
    - system-upgrade # Install personal AUR repos
    - base-software  # Install minimum software/clients to get things done

- name: Run roles based on group appartenance
  hosts: k8s:worker:master:server
  connection: local
  gather_facts: no
  roles:
    - poweroff-schedule # Ensures servers are stopped at the end of day.
