---
- import_playbook: enroll.yml
- import_playbook: in-memory-inventory.yml

- name: Run common configuration tasks
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - repos          # Install personal AUR repos
    - system-upgrade # Install personal AUR repos
    - base-software  # Install minimum software/clients to get things done

- name: Poweroff servers during the night for energy saving
  hosts: servers
  connection: local
  gather_facts: no
  roles:
    - poweroff-schedule

- name: Configure dev user
  hosts: laptops
  connection: local
  gather_facts: no
  roles:
    - users # Ensures the local users are defined

# TODO: Refactor dotfiles to simply copy from/to known locations.
#- name: Configure dotfiles for user jean-philippe
#  hosts: laptops
#  gather_facts: yes
#  become: true
#  become_method: su
#  become_user: jean-philippe
#  roles:
#    - dotfiles
