---
# Note: Ansible is installed on host before running this tooling, so
# no need to reinstall, as upgrades are already handled.
# These are "package themes", which can be added as variable on your
# host if you want to subscribe to those packages
packages:
  common:
    - fish
    - git
    - iproute2
    - lshw
    - mosh
    - most
    - pastebinit
    - python-dnspython
    - python-jmespath
    - python-netaddr
    - python-passlib
    - python-pyopenssl
    - python-systemd
    - ripgrep
    - screen
    - tmux
  desktop:
    - chromium
    - firefox
    - imagemagick
    - libreoffice-fresh
    - python-virtualenv
    - signal-desktop-bin
    - vim
  dev:
    - code
    - docker
    - git-repo
    - git-review
    - hub
    - ipython
    - python-black
    - python-cryptography
    - python-openstackclient
    - python-pygit2
    - python-tox
    - quassel-client-small
    - shellcheck
    - termite
    - tldr
  gnome:
    - gnome
    - arc-gtk-theme
    - arc-icon-theme
    - gnome-themes-extra
    - gtk-engine-murrine
    - seahorse
  k8s:
    - docker
    - k3s
  network:
    - openbsd-netcat
  nognome:
    - acpid
    - arandr
    - compton
    - light
    - lxappearance
    - network-manager-applet
    - pamixer
    - pasystray
    - pavucontrol
    - powerline
    - powerline-vim
    - powerline-fonts
    - rofi
    - scrot
  pass:
    - browserpass
    - browserpass-chromium
    - keybase-gui
    - libu2f-host
    - libusb-compat
    - pass
  pixel:
    - mxt-app-git
    - samus-scripts
  spotify:
    - spotify-dev
  openvpn:
    - openvpn
