---
- name: Define package list
  set_fact:
    _pkglist: |-
      {% set packagelist = [] %}
      {% for pkggroup in pkggroups %}
      {%   set _ = packagelist.append(packages[pkggroup]) %}
      {% endfor %}
      {{ packagelist }}

- name: Install packages
  package:
    name: "{{ _pkglist }}"
    state: present
