---
# package_groups is like a "host var" from vars.yml/in-memory-inventory.
- name: Define package list
  set_fact:
    _pkglist: |-
      {% set packagelist = [] %}
      {% for pkggroup in package_groups %}
      {%   set _ = packagelist.extend(packages[pkggroup]) %}
      {% endfor %}
      {{ packagelist }}

- name: Show list of packages to install
  debug:
    var: _pkglist

- name: Install packages
  package:
    name: "{{ _pkglist }}"
    state: present
