- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: visudo -cf %s

- name: Add the user jean-philippe to all machines
  user:
    name: jean-philippe
    shell: /usr/bin/fish
    append: yes
    groups:
      - wheel

- name: Ensure SSH authorized_keys are up to date
  authorized_key:
    user: jean-philippe
    state: present
    key: https://github.com/evrardjp.keys
