---
- name: Ensure SSH authorized_keys are up to date
  authorized_key:
    user: root
    state: present
    key: https://github.com/evrardjp.keys

- name: Install sshd in case it's needed
  package:
    name: openssh
    state: present

- name: Check if host keys exists
  find:
    path: /etc/ssh
    patterns: "*key"
  register: _hostkeys

- name: Start ssh at least once
  systemd:
    daemon_reload: yes
    name: sshd.service
    state: started
  when: _hostkeys.files | length == 0

- name: Ensure Password Auth is disabled by default
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    regexp: "^PasswordAuthentication"
    state: present
  notify:
    - ssh restart

- name: Ensure SSH can be done freely at home
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match Address 192.168.102.0/24
        PermitRootLogin yes
        PasswordAuthentication yes
    validate: "sshd -t -f %s"
  notify:
    - ssh restart
